import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button } from "@mui/material";
import SignIn from "../components/SignIn";
import React, { useState } from "react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <p>Bienvenido al sistema de tamizaje</p>{" "}
        </h1>

        <Button href={"admin/home"} variant="contained">
          Login
        </Button>

        <SignIn />
      </main>
    </div>
  );
}
